In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
ckd_data = pd.read_csv('./CKD_Dataset/ckd.csv')
ckd_data.head()

,Age,Blood Pressure,Specific Gravity,Albumin,Sugar,Red Blood Cells,Pus Cell,Pus Cell clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery Disease,Appetite,Pedal Edema,Anemia,Class
0,48,70,1.005,4,0,normal,abnormal,present,notpresent,117,...,32,6700,3.9,yes,no,no,poor,yes,yes,1
1,53,90,1.020,2,0,abnormal,abnormal,present,notpresent,70,...,29,12100,3.7,yes,yes,no,poor,no,yes,1
2,63,70,1.010,3,0,abnormal,abnormal,present,notpresent,380,...,32,4500,3.8,yes,yes,no,poor,yes,no,1
3,68,80,1.010,3,2,normal,abnormal,present,present,157,...,16,11000,2.6,yes,yes,yes,poor,yes,no,1
4,61,80,1.015,2,0,abnormal,abnormal,notpresent,notpresent,173,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,1

In [4]:
ckd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      158 non-null    int64
 1   Blood Pressure           158 non-null    int64
 2   Specific Gravity         158 non-null    float64
 3   Albumin                  158 non-null    int64
 4   Sugar                    158 non-null    int64
 5   Red Blood Cells          158 non-null    object
 6   Pus Cell                 158 non-null    object
 7   Pus Cell clumps          158 non-null    object
 8   Bacteria                 158 non-null    object
 9   Blood Glucose Random     158 non-null    int64
 10  Blood Urea               158 non-null    int64
 11  Serum Creatinine         158 non-null    float64
 12  Sodium                   158 non-null    int64
 13  Potassium                158 non-null    float64
 14  Hemoglobin               158 non-null    float64
 15  Packed Cell Volume       158 non-null    int64
 16  White Blood Cell Count   158 non-null    int64
 17  Red Blood Cell Count     158 non-null    float64
 18  Hypertension             158 non-null    object
 19  Diabetes Mellitus        158 non-null    object
 20  Coronary Artery Disease  158 non-null    object
 21  Appetite                 158 non-null    object
 22  Pedal Edema              158 non-null    object
 23  Anemia                   158 non-null    object
 24  Class                    158 non-null    int64
dtypes: float64(5), int64(10), object(10)
memory usage: 31.0+ KB

In [5]:
ckd_data.describe()

,Age,Blood Pressure,Specific Gravity,Albumin,Sugar,Blood Glucose Random,Blood Urea,Serum Creatinine,Sodium,Potassium,Hemoglobin,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Class
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,49.563291,74.050633,1.019873,0.797468,0.253165,131.341772,52.575949,2.188608,138.848101,4.636709,13.687342,41.917722,8475.949367,4.891772,0.272152
std,15.512244,11.175381,0.005499,1.413130,0.813397,64.939832,47.395382,3.077615,7.489421,3.476351,2.882204,9.105164,3126.880181,1.019364,0.446483
min,6.000000,50.000000,1.005000,0.000000,0.000000,70.000000,10.000000,0.400000,111.000000,2.500000,3.100000,9.000000,3800.000000,2.100000,0.000000
25%,39.250000,60.000000,1.020000,0.000000,0.000000,97.000000,26.000000,0.700000,135.000000,3.700000,12.600000,37.500000,6525.000000,4.500000,0.000000
50%,50.500000,80.000000,1.020000,0.000000,0.000000,115.500000,39.500000,1.100000,139.000000,4.500000,14.250000,44.000000,7800.000000,4.950000,0.000000
75%,60.000000,80.000000,1.025000,1.000000,0.000000,131.750000,49.750000,1.600000,144.000000,4.900000,15.775000,48.000000,9775.000000,5.600000,1.000000
max,83.000000,110.000000,1.025000,4.000000,5.000000,490.000000,309.000000,15.200000,150.000000,47.000000,17.800000,54.000000,26400.000000,8.000000,1.000000

In [6]:
ckd_data.isnull().sum()

Age                        0
Blood Pressure             0
Specific Gravity           0
Albumin                    0
Sugar                      0
Red Blood Cells            0
Pus Cell                   0
Pus Cell clumps            0
Bacteria                   0
Blood Glucose Random       0
Blood Urea                 0
Serum Creatinine           0
Sodium                     0
Potassium                  0
Hemoglobin                 0
Packed Cell Volume         0
White Blood Cell Count     0
Red Blood Cell Count       0
Hypertension               0
Diabetes Mellitus          0
Coronary Artery Disease    0
Appetite                   0
Pedal Edema                0
Anemia                     0
Class                      0
dtype: int64

In [7]:
duplicated_data = ckd_data.duplicated().sum()
print(f'The number of duplicated rows in the dataset is: {duplicated_data}')

The number of duplicated rows in the dataset is: 0

In [10]:
ckd_data = ckd_data.rename(columns={'Blood Glucose Random': 'Blood Glucose'})
ckd_data['Blood Glucose'].head()

0    117
1     70
2    380
3    157
4    173
Name: Blood Glucose, dtype: int64

In [11]:
categorical_data = ckd_data.select_dtypes(include=['object'])
categorical_data.head()

,Red Blood Cells,Pus Cell,Pus Cell clumps,Bacteria,Hypertension,Diabetes Mellitus,Coronary Artery Disease,Appetite,Pedal Edema,Anemia
0,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes
1,abnormal,abnormal,present,notpresent,yes,yes,no,poor,no,yes
2,abnormal,abnormal,present,notpresent,yes,yes,no,poor,yes,no
3,normal,abnormal,present,present,yes,yes,yes,poor,yes,no
4,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,poor,yes,yes

In [14]:
def encode_categorical_data(categorical_data,unique_values):
    if len(unique_values) == 2:
        mapping = {unique_values[0]: 0, unique_values[1]: 1}
        categorical_data[column] = categorical_data[column].map(mapping)
    else:
        categorical_data = pd.get_dummies(categorical_data, columns=[column], drop_first=True)
    return categorical_data
    #categorical_data.head()

In [18]:
for column in categorical_data:
    unique_values = categorical_data[column].unique()
    print(f'Column: {column}, Unique Values: {unique_values}')
    categorical_data_encoded = encode_categorical_data(categorical_data, unique_values)

Column: Red Blood Cells, Unique Values: [0 1]
Column: Pus Cell, Unique Values: [0 1]
Column: Pus Cell clumps, Unique Values: [0 1]
Column: Bacteria, Unique Values: [0 1]
Column: Hypertension, Unique Values: [0 1]
Column: Diabetes Mellitus, Unique Values: [0 1]
Column: Coronary Artery Disease, Unique Values: [0 1]
Column: Appetite, Unique Values: [0 1]
Column: Pedal Edema, Unique Values: [0 1]
Column: Anemia, Unique Values: [0 1]

In [19]:
categorical_data_encoded.head()

,Red Blood Cells,Pus Cell,Pus Cell clumps,Bacteria,Hypertension,Diabetes Mellitus,Coronary Artery Disease,Appetite,Pedal Edema,Anemia
0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,1,0,0,1,0
2,1,0,0,0,0,1,0,0,0,1
3,0,0,0,1,0,1,1,0,0,1
4,1,0,1,0,0,1,1,0,0,0

In [20]:
ckd_data[categorical_data_encoded.columns] = categorical_data_encoded
ckd_data.head()

,Age,Blood Pressure,Specific Gravity,Albumin,Sugar,Red Blood Cells,Pus Cell,Pus Cell clumps,Bacteria,Blood Glucose,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery Disease,Appetite,Pedal Edema,Anemia,Class
0,48,70,1.005,4,0,0,0,0,0,117,...,32,6700,3.9,0,0,0,0,0,0,1
1,53,90,1.020,2,0,1,0,0,0,70,...,29,12100,3.7,0,1,0,0,1,0,1
2,63,70,1.010,3,0,1,0,0,0,380,...,32,4500,3.8,0,1,0,0,0,1,1
3,68,80,1.010,3,2,0,0,0,1,157,...,16,11000,2.6,0,1,1,0,0,1,1
4,61,80,1.015,2,0,1,0,1,0,173,...,24,9200,3.2,0,1,1,0,0,0,1